# Generated by Django 4.1.2 on 2023-03-18 09:58

from django.conf import settings
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Certificates',
        ),
        migrations.DeleteModel(
            name='user_data',
        ),
        migrations.AddField(
            model_name='baseuser',
            name='grade',
            field=models.IntegerField(default=False, validators=[django.core.validators.MaxValueValidator(12)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='baseuser',
            name='school',
            field=models.CharField(default='Nava Jyoti', max_length=100),
        ),
    ]
